name: Building nodejs
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checking out to repo
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checking out to repo
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm test
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checking out to repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: building code
        run: npm run build
      - name: deploying code
        run: echo "deployment of code"
      
