name: Building nodejs
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checking out to repo
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
 
      
